language: cpp
compiler:
  - gcc
sudo: false
branches:
  only:
    - client-server
    - master
    - coverity_scan
script:
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
  - make test
addons:
  apt:
    packages:
    - cmake
    - freeglut3-dev
    - libjpeg8-dev
    - libpng12-dev
    - libxmu-dev
    - libxmu-headers
notifications:
  email: false
